### ISSUE TITLE
doesn't work: nothing happens on saving .css file

### ISSUE THREAD

**Issue by tg247** [mikaeljorhult/brackets-autoprefixer#38] opened 2015-03-25 01:28 UTC
Hi all,

I am new in using Brackets (latest on Mac) and Autoprefixer extension. Other extensions run propperly, but Autoprefixer just doesn't do anything.

In brackets.json I have these settings for Autoprefixer:
```json
    "mikaeljorhult.bracketsAutoprefixer.visualCascade": true,
    "mikaeljorhult.bracketsAutoprefixer.browsers": [
        "> 1%",
        "last 2 versions",
        "Firefox ESR",
        "Opera",
        "IE"
    ],
    "mikaeljorhult.bracketsAutoprefixer.enabled": true,
```

If I have understood it right, I just have to turn on "auto prefix on save", make changes to my .css file and hit save. If I'm doing it like that, unfortunately nothing happens.

Do you have any idea, whats going wrong?

Thank you very much for your effort.
Best regards, Thomas

**Comment by MauriceBuiten** [comment] 2015-03-25 17:03
I had at the same problem and found an earlier post that found found the error:

Quote: 

Not entirely sure what I stumbled across as I'm no expert at JSON files, but here's what happened.

I'm on Windows 7 and downloaded the latest release of Brackets (1.2 I believe) and installed the autoprefixer extension. After playing around with it for a while and saving and re-saving css files I could not get it to prefix my css. I could see the options in the Edit menu but it's as if the extension itself just wasn't going.

Eventually I found the brackets.json file which had the autoprefixer settings in it, which were written like this:

"mikaeljorhult.bracketsAutoprefixer.enabled": true,

I looked at the package.json file for autoprefixer and saw that the name was written as:

"mikaeljorhult.brackets-autoprefixer"

So I changed all the preferences in brackets.json to "mikaeljorhult.brackets-autoprefixer" and now it's working perfectly. Not sure what would have caused this or if anyone else has experienced it but I thought it would be worth bringing up.

Thanks

**Comment by tg247** [comment] 2015-03-25 17:26
@MauriceBuiten 
Thank you very much for your comment. 

Unfortunately, changing all the vars to
```javascript
"mikaeljorhult.brackets-autoprefixer"
```
didn't help me. There's still no auto prefixing :( too bad.

**Comment by MauriceBuiten** [comment] 2015-03-25 18:26
Nope, you are right, I did try the same thing and (50 other things) and I cant get this to work either.....

**Comment by RussErdos** [comment] 2015-03-25 19:57
Thanks for the var name change! It worked for me!
 
NOTE: If you use the menu Edit > Autoprefixer Settings... and change anything it will insert the wrong var names and undo your fix.

the fix (worked):
            "mikaeljorhult.brackets-autoprefixer.enabled": true

after using the menu:
inserted this line after my fix:
    (and stopped working):
           "mikaeljorhult.brackets-autoprefixer.enabled": true,
           "mikaeljorhult.bracketsAutoprefixer.enabled": true

**Comment by RussErdos** [comment] 2015-03-31 17:32
Actually, it turned out I needed both. One to keep/sync the "Edit > Auto prefix on save" checked and working.

**Comment by bengoldman** [comment] 2015-05-01 13:15
I am having the same issue, unfortunately.  This extension will not work for me at all in brackets.  I was going to try the above fix, except I don not have the brackets.json file.  Nothing remotely like it in my library/services folder.  I am on a Mac.

**Comment by RussErdos** [comment] 2015-05-01 19:34
Hey Ben, I have updated Brackets and yes can't find brackets.json file either. Also, the extension is not working for me now. Go figure.

**Comment by mikaeljorhult** [comment] 2015-05-04 17:51
This should be resolved by version 0.6.0 that was just released. Please let me know if you run into any problems.

**Comment by tg247** [comment] 2015-05-07 16:04
unfortunately there's still nothing happening.
maybe my settings for the "browser" are wrong?

```
        "> 1%",
        "last 2 versions",
        "Firefox ESR",
        "Opera",
        "IE"
```

do you have any idea?

i am using: Brackets Release 1.3 Build 1.3.0-16022 (release cd0a6aae5) on Mac
and Autoprefixer in version 0.6.0

**Comment by mikaeljorhult** [comment] 2015-05-08 09:26
Have you tried resetting the settings?

**Comment by tg247** [comment] 2015-05-20 10:58
OK, now with the resetted settings it is working. Thank you very much.

these settings didn't work.
```
        "> 1%",
        "last 2 versions",
        "Firefox ESR",
        "Opera 12.1"
```
It seems, "IE" and "Opera 12.1" where causing the problems.

**Comment by mikaeljorhult** [comment] 2015-05-20 11:04
Great! Glad it solved your problem.

**Closed by mikaeljorhult** 2015-05-20 11:04 UTC

**Comment by dc4444** [comment] 2015-12-10 20:33
Still can't get the Auto Prefix Selection to do anything.

Brackets: 
   Release 1.5 build 1.5.0-16538 (release cf9cf4698)

Google Chrome:
   Version 47.0.2526.73 m

My brackets.json look like:

{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "healthData.healthDataTracking": false,
    "mikaeljorhult.brackets-autoprefixer.enabled": true,
    "mikaeljorhult.brackets-autoprefixer.visualCascade": false,
    "mikaeljorhult.brackets-autoprefixer.browsers": [
        "> 1%",
        "last 2 versions",
        "Firefox ESR",
        "Opera 12.1"
    ]
}

ugh...what's wrong?

**Comment by CarrieSchwartz** [comment] 2016-04-24 16:35
Even with re-set and the latest extension I can not get the extension to work. :-(

**Comment by mikhy888** [comment] 2016-06-21 12:50
great pluggin, somhow, its not working with me.. I added the same,  "> 
         1%",
        "last 2 versions",
        "Firefox ESR",
        "Opera 12.1"

:(

**Comment by CraigMac1000** [comment] 2017-04-12 14:49
Hello ppl! Hope someone can help...

Looks like this issue is old now but I have developed the same issue. Works fine when you use it manually Ctrl+shift+P but the autoprefix on save has just stopped working. I recently updated to v1.9 of brackets but have since rolled back to v1.8 but the issue is still there. Any ideas?

**Comment by Mozahedul** [comment] 2017-08-15 06:52
Why everyone is so excited to use Autoprefixer? I recommend everybody to use Emmet. It's an awesome extension. Just install it and write code like -bdrs in your css style. and all the vendor prefixes shows automatically. You can also use this extension for html shortcut...for this see the documentation of emmet.
go this link for documentation... https://docs.emmet.io/abbreviations/syntax/
