### ISSUE TITLE
Brackets Extension Manager often shows Error for this extension

### ISSUE THREAD

**Issue by iAm-Eric** [mikaeljorhult/brackets-autoprefixer#30] opened 2014-12-11 09:13 UTC
Hi.

First, thanks for your work - this Autoprefixer is really second to none vs. all the others (for different editors) out there!

In Brackets I often lost access to the Autoprefixer and the Ext Manager reveals an Error with the extension. I then have to uninstall and reinstall the extension and it will be fine for another day or two.

So far this only happens with Autoprefixer and one other extension, Minify.

This happens on two different Macs, both running Brackets 1.0 and Yosemite.

Any clues? Perhaps it is a Brackets thing?  thanks

**Comment by mikaeljorhult** [comment] 2015-01-17 12:45
Closing this as I'm unable to reproduce the error. Please reopen if problem persists.

**Closed by mikaeljorhult** 2015-01-17 12:45 UTC
